/** Seed data migrated from connect2roots-react-app/src/data/teamMembers.ts */
const PHOTOS = "/C2R Team Photographs";

module.exports = {
	categories: [
		{ title: "Banking, Economics & Financial Services", sortOrder: 0, isAdditional: false },
		{ title: "Artificial Intelligence, GCC, Analytics & Cybersecurity", sortOrder: 1, isAdditional: false },
		{ title: "Engineering & Advanced Research", sortOrder: 2, isAdditional: false },
		{ title: "Agriculture & Sustainable Development", sortOrder: 3, isAdditional: false },
		{ title: "Additional Domain Advisors", sortOrder: 99, isAdditional: true },
	],
	members: [
		{ name: "Amit Singh", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/amitmvit/", bio: "Amit Singh is a leader in mobile connectivity and IoT capabilities across the Indian subcontinent, bringing deep technical leadership across SIM, eSIM, M2M, and enterprise-grade connectivity solutions. With a rare blend of engineering depth and customer-centric execution, he drives end-to-end delivery that turns complex telecom ecosystems into scalable, reliable outcomes." },
		{ name: "Shekhar Prasad", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/prasadshekhar/", bio: "Shekhar Prasad is a seasoned and accomplished Senior Technical Lead with a remarkable career spanning over 16 years in the finance and investment industry. Currently serving in Societe Generale for the past 12 years, Shekhar's technical acumen, combined with his dedication to social causes, reflects a well-rounded professional with a passion for both technological innovation and making a positive difference in the community." },
		{ name: "Anjan Sinha", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/anjan-sinha-0a375325/", bio: "Anjan Sinha is a seasoned full-stack technology professional with over a decade of experience building scalable, dependable digital solutions across global organizations. Known for his sharp problem-solving mindset and execution-driven approach, he brings technical depth, consistency, and long-term vision to the environment. His journey reflects a professional shaped by impact, responsibility, and continuous evolution." },
		{ name: "Karunakar Mohapatra", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/karunakar-mohapatra/", photoUrl: `${PHOTOS}/Krunakar.jpeg`, bio: "Karunakar Mohapatra is a seasoned content strategist and senior editor with over a decade of experience shaping clear, executive-ready narratives for enterprise tech, B2B SaaS, and AI-driven organizations. Known for translating deep technical complexity into structured, trusted storytelling, he operates at the intersection of content, automation, and systems thinking. His work consistently elevates clarity, accuracy, and business relevance at scale." },
		{ name: "Prateek Seth", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/prateek-seth-638b0015/", photoUrl: `${PHOTOS}/prateek seth.jpeg`, bio: "Prateek Seth is a seasoned AWS data and cloud engineering professional with over 13 years of experience delivering secure, scalable, and automated technology solutions across global enterprises. With deep expertise spanning cloud platforms, data engineering, and DevSecOps, he is known for building resilient systems that enable reliability, governance, and long-term digital growth. His work across international environments reflects technical rigor, strategic thinking, and a strong execution mindset." },
		{ name: "Tejana Raithatha", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/tejana-raithatha-89a8bb60/", photoUrl: `${PHOTOS}/Tejana Raithath.png`, bio: "Tejana Raithatha brings a rare blend of analytical rigor and human-centered thinking to the team. With a foundation in engineering and over a decade of experience across operations, marketing, and growth strategy, she approaches business challenges with structured problem-solving and intuitive insight. Her work spans D2C growth, digital strategy, and early-stage ecosystem building, complemented by hands-on mentoring and purpose-driven initiatives. Known for aligning logic with creativity and strategy with execution, Tejana contributes a grounded, reflective perspective that strengthens both business outcomes and long-term impact." },
		{ name: "Rahul Gupta", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/rahul-gupta-iimt/", photoUrl: `${PHOTOS}/rahul gupta.png`, bio: "Rahul Gupta is a people-focused HR professional with a strong foundation in strategic human resource management, talent development, and organizational effectiveness. An MBA from IIM Tiruchirappalli, he is known for crafting data-driven HR strategies that strengthen engagement, culture, and operational excellence. His journey reflects a balanced blend of business acumen, leadership mindset, and continuous improvement." },
		{ name: "Mamta Joshi", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/mamta-joshi-/", photoUrl: `${PHOTOS}/Mamata Joshi.jpeg`, bio: "Mamta Joshi is a strategic marketing and branding professional with over eight years of experience driving growth through data-led storytelling and purpose-driven communication. Known for shaping authentic personal brands and high-impact content ecosystems, she blends strategy, creativity, and execution to build visibility, trust, and sustained engagement. Her work reflects clarity of vision, market intuition, and a results-oriented mindset." },
		{ name: "Archana Kumari", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/archana-kumari-16271b18a", photoUrl: `${PHOTOS}/Archana Kumari_.jpg`, bio: "Archana Kumari brings a strong people-first perspective shaped by experience across technology hiring and financial services. With a sharp eye for talent and an understanding of high-performance environments, she connects capability with opportunity, strengthening teams through trust, precision, and thoughtful decision-making." },
		{ name: "Anilkumar Maurya", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/anilkumar-maurya-65339921/", photoUrl: `${PHOTOS}/anilkumar maurya.jpeg`, bio: "Anilkumar Maurya strengthens our AI and cloud architecture foundation with deep expertise in building intelligent, scalable platforms on Microsoft Azure. From Generative and Agentic AI to enterprise-grade microservices, he brings clarity, structure, and execution rigor to solutions that operate at real-world scale across industries." },
		{ name: "Radheshyam Mishra", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/radheshyam-mishra-6a421734/", photoUrl: `${PHOTOS}/radheshyam mishra.jpeg`, bio: "Radheshyam Mishra is founder and CEO of Parkwiz Technology, he brings deep operational strength to our technology backbone, shaped by years of building, securing, and scaling IT infrastructure across diverse industries. His approach blends execution discipline with long-term vision, ensuring systems that are resilient, efficient, and built to support people and growth at scale." },
		{ name: "Abhilasha Kumari", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/abhilasha-kumari-602134267/", photoUrl: `${PHOTOS}/Abhilasha Kumari.jpeg`, bio: "Abhilasha Kumari is an MBA aspirant driven by curiosity, structure, and a growing interest in how businesses create value through people, processes, and strategy. With a learning-first mindset, she is actively building a strong foundation in management thinking, communication, and problem-solving—preparing herself to contribute meaningfully in dynamic, real-world business environments." },
		{ name: "Rakesh Tiwari", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/rakesh-tiwari-187277208/", photoUrl: `${PHOTOS}/Rakesh Tiwary.jpeg`, bio: "Rakesh Tiwari is a seasoned Total Quality Management leader and Lean Six Sigma Master Black Belt, bringing deep expertise in driving operational excellence across large manufacturing setups. He currently leads TQM implementation across multiple manufacturing units, with a proven track record of Deming Prize–winning transformations, enterprise-wide process improvement, and hands-on quality leadership." },
		{ name: "Avinash Kumar", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/avinash1400/", photoUrl: `${PHOTOS}/Avinash Kumar.jpg`, bio: "Avinash Kumar is a seasoned finance and business leader with deep expertise in project finance, global investments, risk management, and strategic expansion across energy, infrastructure, and education sectors. An Alumni of IIM Bangalore and BIT Mesra, Avinash is a strategy professional, he is currently serving as Associate Director at Finteger Global, Avinash manages a USD 20+ billion debt and hedging portfolio for ACWA Power, overseeing complex financial structures across Asia, the Middle East, and Africa." },
		{ name: "Arvind Sharma", role: "Core Team", panelType: "core", categoryTitle: null, linkedinUrl: "https://www.linkedin.com/in/arvind-kumar-sharma-4925546/", photoUrl: `${PHOTOS}/Arvind Sharma.jpeg`, bio: "Arvind Sharma leads Sales & Marketing with decades of hands-on experience driving growth, building markets, and scaling businesses in the industrial tools sector. From heading large sales organizations to shaping product marketing and revenue strategy, he brings a sharp customer-first approach, strong execution discipline, and a proven track record in business planning, market expansion, and leadership development." },
		{ name: "Shishu Ranjan", role: "Director – Model Risk Management, Barclays India", panelType: "advisory", categoryTitle: "Banking, Economics & Financial Services", linkedinUrl: "https://www.linkedin.com/in/shishu-ranjan-69184123/", photoUrl: `${PHOTOS}/Shishu Ranjan.jpg`, bio: "Shishu Ranjan is an economics and risk management professional with deep expertise in financial modeling, regulatory frameworks, and capital adequacy. With leadership roles across Barclays, HSBC, and PwC, he brings a strong blend of analytical rigor, governance insight, and hands-on experience in managing complex risk ecosystems within global banking institutions." },
		{ name: "Rajeev Ranjan", role: "Head of Alliances & Sales – Fintech", panelType: "advisory", categoryTitle: "Banking, Economics & Financial Services", linkedinUrl: "https://www.linkedin.com/in/rajeevranjan26/", photoUrl: `${PHOTOS}/Rajeev Ranjan.jpeg`, bio: "Rajeev Ranjan is a senior business and alliances leader with deep experience driving strategic partnerships and enterprise sales across global banking, fintech, and technology ecosystems. Having worked across India, Europe, Africa, and emerging markets, he is known for building trust-led relationships, navigating complex markets, and scaling high-impact solutions. His journey reflects strategic foresight, execution strength, and a strong global perspective." },
		{ name: "Vinay Krishna", role: "CEO & Founder – LedgerFi IT Solutions, Pingala Software", panelType: "advisory", categoryTitle: "Artificial Intelligence, GCC, Analytics & Cybersecurity", linkedinUrl: "https://www.linkedin.com/in/vinaykrishna/", photoUrl: `${PHOTOS}/Vinay Krishna.jpeg`, bio: "Vinay Krishna is a technologist, entrepreneur, and thought leader with two decades of experience building and scaling high-impact software organizations. Known for blending agility, servant leadership, and deep technical mastery, he brings a strong focus on digital transformation, agentic AI, and value-driven innovation, along with a legacy of global speaking, research, and community leadership." },
		{ name: "Nitesh Ambuj", role: "Head of Chapter Node – AI & Intelligent Automation, Ericsson", panelType: "advisory", categoryTitle: "Artificial Intelligence, GCC, Analytics & Cybersecurity", linkedinUrl: "https://www.linkedin.com/in/niteshambuj/", photoUrl: `${PHOTOS}/Nitesh Ambuj.jpeg`, bio: "Nitesh Ambuj is a global transformation leader with over two decades of experience shaping innovation-led ecosystems across technology and Global Capability Centers. With deep expertise in AI, intelligent automation, and GCC enablement, he blends strategic vision with hands-on leadership—driving measurable value, mentoring future-ready talent, and building platforms where innovation scales with purpose." },
		{ name: "Naveen Andey", role: "CEO & Founder – Datameadows", panelType: "advisory", categoryTitle: "Artificial Intelligence, GCC, Analytics & Cybersecurity", linkedinUrl: "https://www.linkedin.com/in/naveenandey/", bio: "Naveen Andey is the Founder of Datameadows and leads Analytics with a strong passion for turning data into meaningful business stories. With 15 years of experience in business intelligence and end-to-end analytics projects, he helps organizations derive actionable insights, shape marketing and product strategies, and solve complex business problems across retail, technology, and media sectors. Known for quick turnaround, stakeholder-focused delivery, and hands-on expertise with large datasets and analytics tools, he brings a sharp blend of analytical depth, strategic thinking, and execution excellence." },
		{ name: "Shashank Sinha", role: "Associate Director – RGBSI", panelType: "advisory", categoryTitle: "Engineering & Advanced Research", linkedinUrl: "https://www.linkedin.com/in/shsinha1/", photoUrl: `${PHOTOS}/Shashank Sinha.jpg`, bio: "Shashank Sinha is an engineering leader with deep expertise in advanced simulation and applied research. Graduated from IIT Kanpur and PhD from UCLA, USA, he has a strong foundation in CFD and FEA, his journey spans academic research in the US to leading high-impact engineering teams in industry—bringing rigor, innovation, and problem-solving excellence to complex engineering challenges." },
		{ name: "Rakesh Kumar", role: "Professor – RV College of Engineering", panelType: "advisory", categoryTitle: "Engineering & Advanced Research", linkedinUrl: "https://www.linkedin.com/in/rakesh-kumar-191a0432/", photoUrl: `${PHOTOS}/Rakesh Kumar.jpeg`, bio: "Rakesh Kumar is BTech in Mechanical Engineering from IIT Dhanbad and M.Tech in Thermal Engineering from IIT Kharagpur with PhD from IISc Bangalore, and is currently working as a professor at RV College of Engineering. He is an academic and industry practitioner who bridges deep technical research with real-world engineering impact. With experience spanning advanced research at IISc Bangalore, teaching at leading engineering institutions, and hands-on work in motor and generator design at global firms, he brings a rare blend of analytical rigor, applied innovation, and knowledge leadership." },
		{ name: "Binay Kumar", role: "Domain Advisor – Agriculture & Sustainable Development", panelType: "advisory", categoryTitle: "Agriculture & Sustainable Development", linkedinUrl: "https://www.linkedin.com/in/binay-kumar-singh-8b33809b/", bio: 'Binay Kumar, popularly known as "Man In The Bus" (2015), is a TEDx speaker, a progressive farmer and a software engineer who started his career as a Tech Lead in a multinational software company. After working in the IT sector for more than a decade he realized that it is a never-ending rat race and decided to associate full time with Art of Living to teach progressive farming techniques. Kumar, a trainer in permaculture and other advanced non-invasive farming practices, is teaching fellow Bangaloreans how to grow their own food within their spaces and the urgent need for it. He has been a keynote speaker at multiple public platforms like TEDx, ISTD NATCONF, AICTE, Hyderabad University, IIT-BHU etc. He has also been interviewed by DD Kisan (2016), MH One TV (2018), Sham TV (2018), ABP News (2018) on permaculture. Green TV telecast his videos regularly. At Connect2Roots, he advises on sustainable development initiatives for the Rural Sector.' },
		{ name: "Manish Pathak", role: "Domain Advisor – Banking & Financial Sector", panelType: "advisory", categoryTitle: "Additional Domain Advisors", linkedinUrl: "https://www.linkedin.com/in/manish-pathak-4888243/", photoUrl: `${PHOTOS}/Manish Pathak.jpg`, photoClass: "object-[center_32%] scale-110", bio: "Manish Pathak is a seasoned banking and financial services leader with deep expertise in global engineering, fees & commissions platforms, and large-scale financial systems. With a strong track record across Goldman Sachs and JPMorgan Chase, he brings sharp business–technology alignment, risk-aware execution, and a global perspective to complex financial ecosystems." },
		{ name: "Indrajit Sinha", role: "Founder – SiCAN FinServe Private Limited · Domain Advisor – Banking & Financial Sector", panelType: "advisory", categoryTitle: "Additional Domain Advisors", linkedinUrl: "https://www.linkedin.com/in/indrajit-kumar-9880a91b/", photoUrl: `${PHOTOS}/Indrajit Kumar.jpeg`, bio: "Indrajit Sinha is founder of SiCAN FinServe Private Limited, a seasoned microfinance and banking leader with 18+ years of experience driving financial inclusion at scale. An IRMA alumnus, he has built and expanded large financial operations from the ground up—scaling institutions across geographies, strengthening systems, and leading tech-enabled transformations that deliver sustainable impact in underserved communities." },
	],
};
